name: CI

on:
  pull_request:
  push:
    branches:
      - '**'
    tags-ignore:
      - v*

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
    - uses: actions/checkout@v1
    - name: Install deps
      run: ./install-ubuntu-prereq.sh
    - name: Build
      run: source last.refs && ./build-kvx-llvm.sh test-llvm-build
